schemas:

  bronze:

    acled:
      required_columns:
        - COUNTRY
        - MONTH
        - YEAR
        - EVENTS

    gdelt:
      required_columns:
        - GLOBALEVENTID
        - SQLDATE
        - Actor1CountryCode
        - EventCode
      
  silver:

    acled:
      columns:
        country:          { source: COUNTRY, type: string, nullable: false, primary_key: true }
        month_start_date: { source: month_start_date, type: "datetime64[ns]", nullable: false, primary_key: true }
        num_events:       { source: EVENTS, type: int64, nullable: false }

    gdelt:

      transform_name: silver_gdelt_standard_v1

      columns: 
        event_id:     { source: GLOBALEVENTID, type: string, nullable: false, primary_key: true }
        event_date:   { source: SQLDATE, type: "datetime64[ns]", nullable: false, partition_key: true }
        actor1_name:  { source: Actor1Name, type: string }
        actor2_name:  { source: Actor2Name, type: string }
        num_mentions: { source: NumMentions, type: Int64 }
        num_sources:  { source: NumSources, type: Int64 }
        num_articles: { source: NumArticles, type: Int64 }
        avg_tone:     { source: AvgTone, type: Float64 }

      record_timestamp: _bronze_ingested_at

  gold: 

    acled_monthly:
      inputs:
        acled: { layer: silver, table_name: acled }

      columns:
        month_start_date: { type: "datetime64[ns]", nullable: false }
        total_events: { type: Int64 }

    gdelt_daily: 
      transform_name: gold_gdelt_daily_metrics_v1
     
      inputs: 
        gdelt: { layer: silver, table_name: gdelt }

      columns: 

        event_date:     { type: "datetime64[ns]", nullable: false }
        total_events:   { type: Int64}
        avg_tone:       { type: Float64}
        total_mentions: { type: Int64}
        total_articles: { type: Int64}
      
    gdelt_monthly:
      inputs:
        gdelt: { layer: silver, table_name: gdelt }

      columns:
        month_start_date: { type: "datetime64[ns]", nullable: false }
        total_events:     { type: Int64}
        avg_tone:         { type: Float64}
        total_mentions:   { type: Int64}
        total_articles:   { type: Int64}
             
    conflicts_monthly:
      inputs:
        gdelt: { layer: gold, table_name: gdelt_monthly }
        acled: { layer: gold, table_name: acled_monthly }

      columns:
        month_start_date:   { type: "datetime64[ns]", nullable: false}
        gdelt_total_events: { type: Int64 }
        gdelt_avg_tone:     { type: Float64 }
        acled_total_events: { type: Int64 }