schemas:

  bronze:

    acled:
      file_type: xlsx
      reader:
        sheet_name: 0
        header: 0

      required_columns:
        - COUNTRY
        - MONTH
        - YEAR
        - EVENTS

    gdelt:
      file_type: csv
      reader:
        sep: "\t"
        skipinitialspace: true
        header: null
        names:
          - GLOBALEVENTID
          - SQLDATE
          - MonthYear
          - Year
          - FractionDate
          - Actor1Code
          - Actor1Name
          - Actor1CountryCode
          - Actor1KnownGroupCode
          - Actor1EthnicCode
          - Actor1Religion1Code
          - Actor1Religion2Code
          - Actor1Type1Code
          - Actor1Type2Code
          - Actor1Type3Code
          - Actor2Code
          - Actor2Name
          - Actor2CountryCode
          - Actor2KnownGroupCode
          - Actor2EthnicCode
          - Actor2Religion1Code
          - Actor2Religion2Code
          - Actor2Type1Code
          - Actor2Type2Code
          - Actor2Type3Code
          - IsRootEvent
          - EventCode
          - EventBaseCode
          - EventRootCode
          - QuadClass
          - GoldsteinScale
          - NumMentions
          - NumSources
          - NumArticles
          - AvgTone
          - Actor1Geo_Type
          - Actor1Geo_FullName
          - Actor1Geo_CountryCode
          - Actor1Geo_ADM1Code
          - Actor1Geo_Lat
          - Actor1Geo_Long
          - Actor1Geo_FeatureID
          - Actor2Geo_Type
          - Actor2Geo_FullName
          - Actor2Geo_CountryCode
          - Actor2Geo_ADM1Code
          - Actor2Geo_Lat
          - Actor2Geo_Long
          - Actor2Geo_FeatureID
          - ActionGeo_Type
          - ActionGeo_FullName
          - ActionGeo_CountryCode
          - ActionGeo_ADM1Code
          - ActionGeo_Lat
          - ActionGeo_Long
          - ActionGeo_FeatureID
          - DATEADDED
          - SOURCEURL

      required_columns:
        - GLOBALEVENTID
        - SQLDATE
        - Actor1CountryCode
        - EventCode
      
  silver:

    acled:
      columns:
        country:          { source: COUNTRY, type: string, nullable: false, primary_key: true }
        month_start_date: { source: month_start_date, type: "datetime64[ns]", nullable: false, primary_key: true }
        num_events:       { source: EVENTS, type: int, nullable: false }

    gdelt:

      transform_name: silver_gdelt_standard_v1

      columns: 
        event_id:     { source: GLOBALEVENTID, type: string, nullable: false, primary_key: true }
        event_date:   { source: SQLDATE, type: "datetime64[ns]", nullable: false, partition_key: true }
        actor1_name:  { source: Actor1Name, type: string }
        actor2_name:  { source: Actor2Name, type: string }
        num_mentions: { source: NumMentions, type: int64 }
        num_sources:  { source: NumSources, type: int64 }
        num_articles: { source: NumArticles, type: int64 }
        avg_tone:     { source: AvgTone, type: float64 }

      record_timestamp: _bronze_ingested_at

  gold: 

    acled_monthly:
      inputs:
        acled: { layer: silver, table_name: acled }

      columns:
        month_start_date: { type: "datetime64[ns]", nullable: false }
        total_events: { type: Int64 }

    gdelt_daily: 
      transform_name: gold_gdelt_daily_metrics_v1
     
      inputs: 
        gdelt: { layer: silver, table_name: gdelt }

      columns: 

        event_date:     { type: "datetime64[ns]", nullable: false }
        total_events:   { type: Int64}
        avg_tone:       { type: Float64}
        total_mentions: { type: Int64}
        total_articles: { type: Inullablent64}
      
    gdelt_monthly:
      inputs:
        gdelt: { layer: silver, table_name: gdelt }

      columns:
        month_start_date: { type: "datetime64[ns]", nullable: false }
        total_events:     { type: Int64}
        avg_tone:         { type: Float64}
        total_mentions:   { type: Int64}
        total_articles:   { type: Int64}
             
    conflicts_monthly:
      inputs:
        gdelt: { layer: gold, table_name: gdelt_monthly }
        acled: { layer: gold, table_name: acled_monthly }

      join:
        type: left
        on:
          gdelt.month_start_date: acled.month_start_date

      columns:
        month_start_date:   { type: "datetime64[ns]", nullable: false, partition_key: true }
        gdelt_total_events: { type: Int64 }
        gdelt_avg_tone:     { type: Float64 }
        acled_total_events: { type: Int64 }